// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAFBGlPgjpYpihNT7K3jhnxi-dnu3M_uPE',
    appId: '1:117203870422:web:99556c6b43014e30ef9f77',
    messagingSenderId: '117203870422',
    projectId: 'takshashila-50ca7',
    authDomain: 'takshashila-50ca7.firebaseapp.com',
    databaseURL: 'https://takshashila-50ca7-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'takshashila-50ca7.appspot.com',
    measurementId: 'G-53L503EQ1W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDyPsXypkw-oFJVbdUfuU7EJ1ewK2YVMOY',
    appId: '1:117203870422:android:803d844fec4cba71ef9f77',
    messagingSenderId: '117203870422',
    projectId: 'takshashila-50ca7',
    databaseURL: 'https://takshashila-50ca7-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'takshashila-50ca7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA7oqhEbQALLOTC-MVT2Ucg3pbiZwGe1B8',
    appId: '1:117203870422:ios:22029cecd65c3e70ef9f77',
    messagingSenderId: '117203870422',
    projectId: 'takshashila-50ca7',
    databaseURL: 'https://takshashila-50ca7-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'takshashila-50ca7.appspot.com',
    iosClientId: '117203870422-urtk7ipfc37o3je9j4m2ujucv1ps888m.apps.googleusercontent.com',
    iosBundleId: 'com.example.takshashila',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA7oqhEbQALLOTC-MVT2Ucg3pbiZwGe1B8',
    appId: '1:117203870422:ios:693d3bd2dd3e283eef9f77',
    messagingSenderId: '117203870422',
    projectId: 'takshashila-50ca7',
    databaseURL: 'https://takshashila-50ca7-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'takshashila-50ca7.appspot.com',
    iosClientId: '117203870422-jdq5j0i4973evfficbtd7eakt3ojedp4.apps.googleusercontent.com',
    iosBundleId: 'com.example.takshashila.RunnerTests',
  );
}
